export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkRhbmllbCBBIFBlZHJvc28iLCJlbWFpbCI6ImRhbmllQGRhLmNvbSIsImlhdCI6MTY4MDYxNTkyNywiZXhwIjoxNjgwNzAyMzI3LCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMSJ9.kWl1P_gVdmCFGx5TjBQygAA6xv0TKvHdK-Og1PQKHXA';
